baseurl = "https://www.mattallford.com"
DefaultContentLanguage = "en"
title = "Matt Allford"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[services.disqus]
  shortname = "mattallford"

[markup.goldmark.renderer]
  unsafe = true

[params]
  mainSections = ["post", "posts"]
  author = "Matt Allford"
  dateFormat = "January 2, 2006"
  description = "Writing about Azure, infrastructure, and technology."
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = false
  comments = true

  [params.homeInfoParams]
    Title = ""
    Content = """
Hi, I'm Matt. A technologist, content creator, and generally curious person. If you've \
stumbled across this site, it's where I write some ramblings, usually about \
technology, or technology adjacent. Check out the [About](/about/) page for more information, \
and please feel free to connect with me on one of the social platforms linked below.

Thanks for stopping by!
"""

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/mattallford"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/mattallford"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/mattallford"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCWPrPzVnLa9ma7axTJgUX0Q"

  [[params.socialIcons]]
    name = "mastodon"
    url = "https://mastodon.social/@mattallford"

  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 1

[[menu.main]]
  name = "Content Portfolio"
  url = "/content-portfolio/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 4
